FROM python:3.9.7-buster
ARG DEBIAN_FRONTEND=nonine

RUN apt-get update && apt-get install -y tzdata libgl1-mesa-dev\
&& ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

ENV TZ=Asia/Tokyo

RUN python3 -m pip install --upgrade pip \
&& pip install --no-cache-dir \
   black \
   jupyterlab\
   jupyterlab_code_formatter \
    jupyterlab-git \
    lckr-jupyterlab-variableinspector \
    jupyterlab_widgets \
    ipywidgets \
    import-ipynb

RUN pip install --no-cache-dir \
    numpy \
    pandas \
    matplotlib \
    pillow \
    spectral \
    mplcursors \
    ipympl \
    japanize-matplotlib \
    scipy \
    seaborn \
    opencv-contrib-python



