version: "3.9"
services:
  py3:
    build:
      context: ./py3
      dockerfile: dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./py3/root_jupyter:/root/.jupyter
      - ./workspace:/workspace
      - /mnt/f/study_data:/data
      - /mnt/c/Windows/Fonts:/Fonts

      